# -*- coding: utf-8 -*-
"""a-algo-dever14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smFEKOxRoyCySA5RbE60-UEIdatKtfJx

# **Homework 14**

O grupo não publicou a apresentação com o dever de casa até o prazo da aula do dia 12.
"""

