# -*- coding: utf-8 -*-
"""a-algo-dever15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBS632lD2WTuaWwjwGMhpfnotHsQHPjN

# **Homework 15**

O grupo não publicou o slide até dia 15/06.
"""

