# -*- coding: utf-8 -*-
"""a-algo-dever1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15oIm-WNyh2AYGu4ky4Tk1cFlUQkTqKFH

# **Homework - The n² Barrier**

## Objective

Empirically compare the efficiency of two sorting methods and identify the "breaking point" where asymptotic theory becomes visible in practice.

## Exercise

Implement the Insertion Sort O(𝒏²) algorithm – DO NOT USE AI in the implementation, as the algorithm may appear on the exam.

Use the native Python function sorted() (which uses Timsort, (𝒏 log 𝒏)) for comparison purposes.

Generate random lists of sizes n = [1000, 5000, 10000, 20000, 50000].

Measure the execution time of both algorithms for each 𝒏, generating the output in the terminal for each of them.

Use the time library.

# **Configuration**
"""

"""
Install pt_BR
"""
!/usr/share/locales/install-language-pack pt_BR
!dpkg-reconfigure locales

"""
Restart the Python process
"""
os.kill(os.getpid(), 9)

"""# **Implementation**"""

import datetime as dt
import numpy as np
import os
import random as rnd
import zoneinfo as zi

"""
Setting example constants.
"""
values = []
SZ_1ML = 1000
SZ_5ML = 5000
SZ_10ML = 10000
SZ_20ML = 20000
SZ_50ML = 50000

"""
Setting the zone info
"""
tz = zi.ZoneInfo("America/Sao_Paulo")

"""
Adding random values in variable "VALUES".
"""
def generate_numbers(size):
    for i in range(size):
        values.append(int(rnd.random() * 100))
    return values

"""
Function insertionsort (n²).
"""
def insertion_sort(num: int):
  values.clear()
  generate_numbers(num)
  print(f"\x1b[31;1mInsertion Sort (n²) - With {num} itens:\x1b[0m")
  start = dt.datetime.now(tz)
  print(f"\t\x1b[31;1m[Start]⇨ {start}\x1b[0m")

  for x in range(len(values)):
    key = values[x]
    y = x - 1

    while y >= 0 and key < values[y]:
      values[y + 1] = values[y]
      y -= 1
    values[y + 1] = key

  end = dt.datetime.now(tz)
  print(f"\t\x1b[31;1m[End]⇨ {end}\x1b[0m")
  print(f"\t\x1b[31;1m[Interval]⇨ {(end-start).microseconds}ms\x1b[0m")
  breakline()

"""
Function timsort (n log n).
"""
def tim_sort(num: int):
  values.clear()
  generate_numbers(num)
  print(f"\x1b[34;1mTim Sort (n log n) - With {num} itens:\x1b[0m")
  start = dt.datetime.now(tz)
  print(f"\t\x1b[34;1m[Start]⇨ {start}\x1b[0m")
  values.sort()
  end = dt.datetime.now(tz)
  print(f"\t\x1b[34;1m[End]⇨ {end}\x1b[0m")
  print(f"\t\x1b[34;1m[Interval]⇨ {(end-start).microseconds}ms\x1b[0m")
  breakline()

"""
Function breakline
"""
def breakline():
  print("\n")

"""
Calling functions to compare then.
"""
insertion_sort(SZ_1ML)
insertion_sort(SZ_5ML)
insertion_sort(SZ_10ML)
insertion_sort(SZ_20ML)
insertion_sort(SZ_50ML)
tim_sort(SZ_1ML)
tim_sort(SZ_5ML)
tim_sort(SZ_10ML)
tim_sort(SZ_20ML)
tim_sort(SZ_50ML)
breakline()
print("End of process.")