# -*- coding: utf-8 -*-
"""a-algo-dever-sala-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQGdP-Pn5kAfAY71jd-FnGUbotsiMgTs

# **Classroom Homework 1**

Given a string of size n, find all possible substrings.

A substring can have from 1 to n characters. They must be in the same order as the original string.

Develop the reasoning with the 4 steps for recursion. Note the steps as comments in the code.

Implement and test the code.

Call the teacher to analyze it.

## **Configuration**
"""

"""
Install pt_BR
"""
!/usr/share/locales/install-language-pack pt_BR
!dpkg-reconfigure locales

"""
Restart the Python process
"""
os.kill(os.getpid(), 9)

"""## **Implementation**"""

import datetime as dt
import numpy as np
import os
import random as rnd
import zoneinfo as zi
import string as strg

"""
Setting the zone info
"""
tz = zi.ZoneInfo("America/Sao_Paulo")

"""
First Step: Knowing what the function should do:
# The code is not yet needed for analysis.
# The described function attempts to return the possible substrings within an input string.

Second Step: Select a subproblem and assume that the function already works on it.
# Using recursive thinking:

# Original string = abc
# a b c ab bc abc

# If the string is null, return the empty array. Else build the array with all subtrings starting from the first character.

Third Step: Use the value returned from the previous problem to construct the solution to the original problem.

Fourth Step: Identify the base case.
"""
mystr = "abc"
substrings = []

def get_substrings(mystr: strg):
  if len(mystr) == 0:
    return substrings
  else:
    for i in range(len(mystr)):
      substrings.append(mystr[0:i+1])

  return get_substrings(mystr[1:])

print(f"\x1b[34mSubstrings founded: ", get_substrings(mystr), "\x1b[0m")