# -*- coding: utf-8 -*-
"""a-algo-dever2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ySnXJfNQw5Dm8Q7ok8-oV_B8pT10m6w

# **Homework - Fatorial Implementation**

Implement a Python algorithm that calculates the factorial of a number using recursion. After that, determine the asymptotic complexity O(n) of the algorithm, including an explanation of the reasoning. The goal is to evaluate how the execution time increases as a function of the input size n.

### Instructions:

Write a Python program that:

Reads an integer n.

Calculates the factorial of n recursively.

Include comments explaining each part of the code.

Measures the execution time of the algorithm for different values ​​of n: 10, 100, 500, and 1000.

Submit the code with the execution time results and a brief explanation of the complexity analysis.

# **Configuration**
"""

"""
Install pt_BR
"""
!/usr/share/locales/install-language-pack pt_BR
!dpkg-reconfigure locales

"""
Restart the Python process
"""
os.kill(os.getpid(), 9)

"""## **Implementation**"""

import datetime as dt
import numpy as np
import os
import random as rnd
import zoneinfo as zi

"""
Setting the zone info
"""
tz = zi.ZoneInfo("America/Sao_Paulo")

"""
Setting constants and variables.
"""
QUANTIFIERS = [10, 100, 500, 1000]

"""
Factorial function
"""
def factorial(n: int):
  if n == 0: # validate if n is 0 or not.
    return 1 # if n is equal 0, return 1.
  rst = n * factorial(n-1) # calc of factorial.
  return rst # return the final value of factorial.

"""
Function breakline
"""
def breakline():
  print("\n")

"""
Loop with requested values
"""
for i in range(len(QUANTIFIERS)):
  print(f"\x1b[36;1mFactorial - With {QUANTIFIERS[i]} itens:\x1b[0m")
  start = dt.datetime.now(tz)
  print(f"\t\x1b[36;1m[Start]⇨ {start}\x1b[0m")

  complexity = 8*QUANTIFIERS[i] # complexity of function.
  print(f"\t\x1b[35;2m[Complexity]⇨ {complexity}\x1b[0m")

  factorial(QUANTIFIERS[i])

  end = dt.datetime.now(tz)
  print(f"\t\x1b[36;1m[End]⇨ {end}\x1b[0m")
  print(f"\t\x1b[36;1m[Interval]⇨ {(end-start).microseconds}ms\x1b[0m")
  breakline()

print(f"\x1b[95;1mThe factorial algorithm with recursive implementation has a complexity of type Linear O(n).",
      "\nThe asymptotic mathematics found was: \'8 * n times\'.",
      "\n\nFunction factorial:",
      "\n\tLine 1 ⇨ 1 access + 1 comparation",
      "\n\tLine 2 ⇨ 1 return",
      "\n\tLine 3 ⇨ 1 assignment + 1 operation + 1 call function + 1 operation",
      "\n\tLine 4 ⇨ 1 return")