# -*- coding: utf-8 -*-
"""a-algo-dever4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwDkck8HWN980VKHmX5XJd0F-EwC0_Cj

# **Homework 4**

Consider the following recursive function:

F(n)=2\*F(n-1)+n\*2

with the base case F(1)=2

Task:
* Implement this function in Python using recursion.
* The program should ask the user for a value of n and calculate F(n).

## **Configuration**
"""

import os
import zoneinfo as zi

"""
Install pt_BR
"""
!/usr/share/locales/install-language-pack pt_BR
!dpkg-reconfigure locales

"""
Restart the Python process
"""
os.kill(os.getpid(), 9)

"""## **Implementation**"""

import zoneinfo as zi

"""
Setting the zone info
"""
tz = zi.ZoneInfo("America/Sao_Paulo")

"""
F(n) function
"""
def F(n):
    if n == 1:
        return 2

    return 2 * F(n - 1) + n * 2

n = int(input("Insert one value of n: "))

result = F(n)
print(f"\x1b[34;1mF({n}) = {result}\x1b[0m")