# -*- coding: utf-8 -*-
"""a-algo-dever8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JxzBAxSCK6tKE1QoaDFXvxUhcxwaqav9

# **Homework 8**

O grupo da apresentação não revelou o dever de casa, logo não há deveres para essa parte 8.
"""

