# -*- coding: utf-8 -*-
"""a-algo-dever-sala-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fYRszcfS0SV_lTuGqgJHN0MfTBN8gHH

# **Classroom Homework 2.1**

Implement recursive functions in Python that calculate the value of F(n) according to the following recurrences:

- F(n) = F(n-1)+n+1 with the base case F(0)=1
- F(n) = F(n-1)+3n+2 with the base case F(1)=1
- Create a program that asks the user for a value of n and returns the values ​of F(n) to the function.

## **Configuration**
"""

"""
Install pt_BR
"""
!/usr/share/locales/install-language-pack pt_BR
!dpkg-reconfigure locales

"""
Restart the Python process
"""
os.kill(os.getpid(), 9)

"""## **Implementation**"""

import datetime as dt
import numpy as np
import os
import random as rnd
import zoneinfo as zi
import string as strg

"""
Setting the zone info
"""
tz = zi.ZoneInfo("America/Sao_Paulo")

"""
Function 1: F(n) = F(n-1) + n + 1, com F(0) = 1
"""
def F1(n):
    if n == 0:
        return 1
    else:
        return F1(n - 1) + n + 1

"""
Function 2: F(n) = F(n-1) + 3n + 2, com F(1) = 1
"""
def F2(n):
    if n == 1:
        return 1
    elif n < 1:
        raise ValueError("n must be >= 1 to F2")
    else:
        return F2(n - 1) + 3*n + 2

"""
Main program
"""
def main():
    n = int(input("Insert one value to n: "))

    # Calculating F1(n)
    valor_F1 = F1(n)
    print(f"F1({n}) = {valor_F1}")

    # Calculating F2(n)
    if n >= 1:
        valor_F2 = F2(n)
        print(f"F2({n}) = {valor_F2}")
    else:
        print("F2 não é definida para n < 1")


if __name__ == "__main__":
    main()

"""## **Classroom Homework 2.2**

Implement a recursive function that calculates F(n) according to the following recurrence:

F(n) = F(n/2) + 3F(n)

with the condition that n is a power of 2 and the base case returns 5.

The program should:

Prompt the user for a value of n (check if it is a power of 2).

Calculate and print F(n).
"""

"""
Is power of 2 function
"""
def is_pow_of_2(n):
    return n > 0

"""
F(n) function
"""
def F(n):
    if n == 1:
        return 5

    return F(n // 2) + 3 * n

n = int(input("Insert one value of n (pow of 2): "))

if not is_pow_of_2(n):
    print("\x1b[31;1mError: n must be one power of 2.\x1b[0m")
else:
    result = F(n)
    print(f"\x1b[34;1mF({n}) = {result}\x1b[0m")