# -*- coding: utf-8 -*-
"""a-algo-dever-sala3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SebWcT_Z2wARutnARtl_r_OSyOku9wzs

# **Classroom Homework 3**

Analisador de Complexidade com Teorema Mestre

## **Objetivo**:

Desenvolver um programa que auxilie na análise da complexidade de algoritmos de divisão e conquista utilizando o Teorema Mestre.

Descrição do exercício

## **Entrada**:

O programa deve receber como entrada os parâmetros da relação
de recorrência no formato T(n) = aT(n/b) + f(n).

Especificamente, o programa deve solicitar ao usuário os valores
de:

a (número de subproblemas)

b (fator de redução do tamanho do problema)

f(n) (custo do trabalho fora das chamadas recursivas)

Para simplificar, limite f(n) a funções polinomiais do tipo n k *log

## **Processamento**:

O programa deve implementar a lógica do Teorema Mestre para determinar a complexidade assintótica em relação a recorrência fornecida.

O programa deve identificar em qual caso o Teorema Mestre se aplica (caso 1, 2 ou 3)

O programa deve realizar os cálculos necessários para comparar f(n) com n^log b a

## **Exemplo**:

Digite o valor de a: 4

Digite o valor de b: 2

Digite o valor de k (expoente de n em f(n)): 2

Digite o valor de p (expoente de log(n) em f(n)): 0

Entrada: a=4, b=2, k=2, p=0, f(n) = n^2

Caso do Teorema Mestre: Caso 1

### **Desafios Bons**:

Torre de Hanoi;<br>
Cubo Mágico;<br>

## **Configuration**
"""

"""
Install pt_BR
"""
!/usr/share/locales/install-language-pack pt_BR
!dpkg-reconfigure locales

"""
Restart the Python process
"""
os.kill(os.getpid(), 9)

"""## **Implementation**"""

import os
import math
import zoneinfo as zi

"""
Setting the zone info
"""
tz = zi.ZoneInfo("America/Sao_Paulo")

"""
Complexity Analizer Function
"""
def complexity_analizer():
  a = int(input("Insert the value of a: "))
  b = int(input("Insert the value of b: "))
  k = float(input("Insert the value of k (exponent of n in f(n)): "))
  p = float(input("Insert the value of p (exponent of log(n) in f(n)): "))


  print(f"\nEntry: a={a}, b={b}, f(n)=n^{k:.2f}(log n)^{p:.2f}")

  if b <= 1:
      print("Error: 'b' must be greater than 1 for the Master Theorem.")
      return
  if a < 1:
      print("Error: 'a' must be greater than or equal to 1 for the Master Theorem.")
      return

  log_b_a = math.log(a, b)
  print(f"n^(log_b a) = n^{log_b_a:.2f}")

  complexity_str = ""
  case_num = 0

  """
  Case 1: f(n) = O(n^(log_b a - epsilon))
  This occurs when k < log_b_a

  Case 2: f(n) = Θ(n^(log_b a) * (log n)^p) for p >= 0
  This occurs when k == log_b_a

  If k = log_b_a but p < 0, f(n) is asymptotically smaller than n^(log_b a)
  as (log n)^p approaches 0. This effectively falls into Case 1.

  Case 3: f(n) = Ω(n^(log_b a + epsilon)) AND regularity condition
  This occurs when k > log_b_a

  The regularity condition: a * f(n/b) <= c * f(n) for some c < 1 and sufficiently large n
  For f(n) = n^k * (log n)^p, this typically holds if a / b^k < 1.
  Since k > log_b_a, then b^k > b^(log_b_a) = a, so a/b^k < 1 is generally true.
  Thus, the regularity condition is usually met for this form of f(n).
  """
  if k < log_b_a:
    case_num = 1
    complexity_str = f"Θ(n^{log_b_a:.2f})"
  elif k == log_b_a:
    case_num = 2
    if p >= 0:
        complexity_str = f"Θ(n^{log_b_a:.2f} * (log n)^{p+1:.2f})"
    else:
        case_num = 1
        print("Note: For k = log_b a and p < 0, f(n) is polynomially smaller than n^(log_b a). Applying Case 1 logic.")
        complexity_str = f"Θ(n^{log_b_a:.2f})"
  elif k > log_b_a:
    if a < (b**k):
      case_num = 3
      complexity_str = f"Θ(n^{k:.2f} * (log n)^{p:.2f})"
    else:
      print("Could not apply Master Theorem (regularity condition not met for Case 3 or f(n) not in specified form).")
      return
  else:
      print("Could not apply Master Theorem (conditions not met). This might occur due to floating point precision issues for k and log_b_a). Please try adjusting k slightly if k is intended to be exactly log_b_a.")
      return

  print(f"Master Theorem Case: Case {case_num}")
  print(f"Complexity: {complexity_str}")

complexity_analizer()