# -*- coding: utf-8 -*-
"""a-algo-dever3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kx_SaP_NzPpr_XsI-C1eRvcDtnBbxaWR

# **Homework of Palindrome**

Implement the recursive code to check if an array is a palindrome.

Examples:

array1 = [0, 1, 2, 3, 2, 1, 0] -> Is a palindrome

array2 = ["a", "b", "b", "a"] -> Is a palindrome

array3 = ["a", "b", "c", "b", "a"] -> Is a palindrome

array4 = ["a", "b", "c", "f", "b", "a"] -> Is not a palindrome

## **Configuration**
"""

"""
Install pt_BR
"""
!/usr/share/locales/install-language-pack pt_BR
!dpkg-reconfigure locales

"""
Restart the Python process
"""
os.kill(os.getpid(), 9)

"""## **Implementation**"""

import datetime as dt
import numpy as np
import os
import random as rnd
import zoneinfo as zi
import array as arr

"""
Setting the zone info
"""
tz = zi.ZoneInfo("America/Sao_Paulo")

"""
Palindrome implementation with definition of array before.
"""
myarr = ['a', 'b', 'c', 'c', 'b', 'a']

def palindrome(list: arr):
  if len(list) % 2 != 0:
    print("\x1b[31;1mIsn't a palindrome!\x1b[0m")
  else:
    tam_total = int(len(list))
    tam_metade = int(len(list)/2)
    normal = list[0:tam_metade]
    reverse = list[tam_metade:tam_total]
    reverse.reverse()
    if normal == reverse:
      print("\x1b[34;1mIs a palindrome!\x1b[0m")
    else:
      print("\x1b[31;1mIsn't a palindrome!\x1b[0m")

palindrome(myarr)