# -*- coding: utf-8 -*-
"""a-algo-dever12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nzi0Ad2MXb9ByWnvNxHmIgDxFZ7nIQ74

# **Homework 12**

A atividade não pode ser feita, porque o grupo não divulgou o dever de casa.
"""

